swagger:
  basepackage: com.itheima.security.distributed.order.uaa.config  #扫描api包路径扫描SwaggerConfig2.java所在api包路径
  service:
    name: order订单 #api名称
    description: 资源服务 #api描述
    developer: 陈亮 #api开发者
  auth:
    server:   #使用哪种认证方式,我这里没填
  is:
    enable: true #是否激活swagger开
